version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    entrypoint: [ "/bin/bash", "-c", "bash ./scripts/prestart.sh && poetry run python manage.py runserver 0.0.0.0:8000" ]

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume: